### ISSUE TITLE
upscaled_sraa not working with parameter rep AND h

### ISSUE THREAD

**Issue by Ichunjo** [Irrational-Encoding-Wizardry/lvsfunc#5] opened 2019-10-29 19:37 UTC
```py
scaled = lvf.upscaled_sraa(contrasharp, 2, 13, 1080)
```

```Failed to evaluate the script:
Python exception: Repair: Input clips must have the same format

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
File "F:\VPS\ENCO EN COURS\Island\island01.vpy", line 39, in 
scaled = lvf.upscaled_sraa(contrasharp, 2, None, 1080)
File "C:\Users\Varde\AppData\Local\Programs\Python\Python37\Lib\lvsfunc.py", line 342, in upscaled_sraa
return core.resize.Spline36(aa_y, w, h) if rep is None else core.resize.Spline36(aa_y, w, h).rgvs.Repair(clip, rep)
File "src\cython\vapoursynth.pyx", line 1833, in vapoursynth.Function.__call__
vapoursynth.Error: Repair: Input clips must have the same format```

**Comment by LightArrowsEXE** [comment] 2019-10-29 19:40
This is caused by the repair using the old not-rescaled clip. This can be fixed by either repairing before downscaling or disabling the repair if a custom resolution is set. Will fix this in a bit.

**Closed** 2019-10-31 08:56 UTC
