### ISSUE TITLE
detail_mask takes parameter for chroma, but doesn't use it

### ISSUE THREAD

**Issue by dixie-flatliner** [Irrational-Encoding-Wizardry/lvsfunc#71] opened 2021-09-17 20:47 UTC
Both masks are made from luma only.

Maybe this is intended (idk), but I thought it was odd.

**Comment by LightArrowsEXE** [comment] 2021-09-17 21:42
Duplicate of #55? That said, I am aware of issues concerning `detail_mask`, and have had a prototype for an improved version lying around that still has yet to be finalised. Posting it here so people can read this issue and test it out for the time being.

```py
def detail_mask(clip: vs.VideoNode,
                sigma: float = 1.0, rxsigma: List[int] = [50, 200, 350],
                pf_sigma: Optional[float] = 1.0,
                rad: int = 3, brz: Tuple[int, int] = (2500, 4500),
                rg_mode: int = 17,
                ) -> vs.VideoNode:
    """
    A detail mask aimed at preserving as much detail as possible within darker areas,
    even if it contains mostly noise.
    """
    from kagefunc import kirsch
    from vsutil import depth, get_y, iterate

    bits, clip = _get_bits(clip)

    clip_y = get_y(clip)
    pf = core.bilateral.Gaussian(clip_y, sigma=pf_sigma) if pf_sigma else clip_y
    ret = core.retinex.MSRCP(pf, sigma=rxsigma, upper_thr=0.005)

    blur_ret = core.bilateral.Gaussian(ret, sigma=sigma)
    blur_ret_diff = core.std.Expr([blur_ret, ret], "x y -")
    blur_ret_dfl = core.std.Deflate(blur_ret_diff)
    blur_ret_ifl = iterate(blur_ret_dfl, core.std.Inflate, 4)
    blur_ret_brz = core.std.Binarize(blur_ret_ifl, brz[0])
    blur_ret_brz = core.morpho.Close(blur_ret_brz, size=8)

    kirsch_mask = kirsch(clip_y).std.Binarize(brz[1])
    kirsch_ifl = kirsch_mask.std.Deflate().std.Inflate()
    kirsch_brz = core.std.Binarize(kirsch_ifl, brz[1])
    kirsch_brz = core.morpho.Close(kirsch_brz, size=4)

    merged = core.std.Expr([blur_ret_brz, kirsch_brz], "x y +")
    rm_grain = core.rgvs.RemoveGrain(merged, rg_mode)
    return rm_grain if bits == 16 else depth(rm_grain, bits)
```

Thanks for reporting!

**Comment by dixie-flatliner** [comment] 2021-09-17 21:46
Sorry, I just skimmed the titles of the closed issues.

New mask looks interesting; don't feel qualified to say more though.

**Comment by dnjulek** [comment] 2021-09-18 17:20
Where is this `rad: int = 3` used?

**Comment by LightArrowsEXE** [comment] 2021-09-18 17:21
> Where is this `rad: int = 3` used?

Nowhere, it seems. It used to be used, but I forgot to remove it from the param list after reworking that section, I believe.

**Closed** 2021-09-28 00:29 UTC
Labels: bug
